spring.application.name=lifevault

spring.datasource.url=jdbc:mysql://localhost:3306/lifevault_db
spring.datasource.username=root
spring.datasource.password=@Kana1137

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
